# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3722ff568679804582ee606c9dc05fdf848bb1e2310dba52bcf8076f25c7d3a9ed173b4e3332c5714de73f8b5f2dfca36f715464394e00c55b710c9f7f31f5cc

test:
  secret_key_base: 9c61d536f8671b6ae4a3c0b7ca3232e7dcca44f29b2a99358db7133bc94f3d29265056e4d5ffbc22624cb25524df4a67eb445ee29f950503569a3a2ce65c6bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
